* Magit

Magit is a program to the Git version control system. It is en grained as a package in Emacs. Magit isn't perfect (as in the fact that it can improve and wrap every git command), but it still can preform usual version control commands.

*Personal access token*

The Personal access token or PAT in GitHub is another way to sign into your GitHub account. The password for the access token will help also when you are signing into your GitHub page. The only thing about the password for the access token is that it is pretty long. So, if you sign in to GitHub with the password of your access token, make sure you have your password saved.

*Storing GitHub username/password for Emacs/doomEmacs*

When fetching, pulling, and/or pushing a repository from GitHub using doomEmacs, it asks for my github username and password every time I perform a git operation (pull,push, fetch) from my gitHub repository. It's a hassle/annoying!!

For that, all what I did is pulled changes from my repository using doomEmacs, then enter  /username/password/ (personal access token, generated for commandline git operation!). Then open /eshell/ and enter the following command

#+begin_quote
git config --global credential.helper store
#+end_quote


* Git Operations using Command line
A few useful Git operations using command line are:
 - git add: You use this command to add a file.
 - git commit-m (type commit message): Use this command to type a commit message when you are pushing edits you made to your GitHub page.
 - git reset: You are resetting a file
