* Magit



*Personal access token*

The Personal access token or PAT in GitHub is another way to sign into your GitHub account. The password for the access token will help also when you are signing into your GitHub page. The only thing about the password for the access token is that it is pretty long. So, if you sign in to GitHub with the password of your access token, make sure you have your password saved.

*Storing GitHub username/password for Emacs/doomEmacs*

When fetching, pulling, and/or pushing a repository from GitHub using Doomemacs, it asks for my github username and password every time I perform a git operation (pull,push, fetch) from my gitHub repository. It's a hassle/annoying!!

For that, all what I did is pulled changes from my repository using doomEmacs, then enter  /username/password/ (personal access token, generated for commandline git operation!). Then open /eshell/ and enter the following command

#+begin_quote
git config --global credential.helper store
#+end_quote


* Git Operations using Command line
